// GENERATED by Style Dictionary — do not edit by hand.
// Novakid token tree. Example: tokens.color.background.brand.default
export const tokens = {
  "color": {
    "violet": {
      "100": "#F7F5FF",
      "200": "#CFCFFD",
      "300": "#AAA8FB",
      "400": "#887DFA",
      "500": "#6D46FC",
      "600": "#572BD7",
      "700": "#420EAE",
      "800": "#2E1781",
      "900": "#170751",
      "1000": "#070026"
    },
    "blue": {
      "100": "#F3F7FF",
      "200": "#BAD2FD",
      "300": "#82ADFB",
      "400": "#4784F9",
      "500": "#0A58EA",
      "600": "#0645BD",
      "700": "#023392",
      "800": "#00216A",
      "900": "#001046",
      "1000": "#00002C"
    },
    "magenta": {
      "100": "#F9F1FE",
      "200": "#EED4FD",
      "300": "#DFABF7",
      "400": "#D78FFB",
      "500": "#C76EF2",
      "600": "#A14EC7",
      "700": "#7C309D",
      "800": "#581074",
      "900": "#330146",
      "1000": "#11001B"
    },
    "coral": {
      "100": "#FFF3F3",
      "200": "#FED4CF",
      "300": "#FDB2AA",
      "400": "#FC8C84",
      "500": "#FF5A56",
      "600": "#D23A3A",
      "700": "#A5161F",
      "800": "#730710",
      "900": "#430105",
      "1000": "#190000"
    },
    "green": {
      "100": "#E9FBF0",
      "200": "#D1FCD6",
      "300": "#B7FDBB",
      "400": "#9AFD9E",
      "500": "#79FD7F",
      "600": "#4CC855",
      "700": "#1C952C",
      "800": "#0B6318",
      "900": "#023407",
      "1000": "#000C00"
    },
    "orange": {
      "100": "#FFF3E7",
      "200": "#FEE7CE",
      "300": "#FDCD9B",
      "400": "#FCB86B",
      "500": "#FFA000",
      "600": "#C67E18",
      "700": "#925C0E",
      "800": "#623C05",
      "900": "#361E00",
      "1000": "#110400"
    },
    "yellow": {
      "100": "#FFF9CC",
      "200": "#FFF5AD",
      "300": "#FFF08A",
      "400": "#FFEB60",
      "500": "#FFE60A",
      "600": "#C6B321",
      "700": "#908215",
      "800": "#5E5509",
      "900": "#312B01",
      "1000": "#0A0700"
    },
    "grey": {
      "100": "#F5F5F5",
      "200": "#D7D7D7",
      "300": "#B9B9B9",
      "400": "#9B9B9B",
      "500": "#7F7F7F",
      "600": "#636363",
      "700": "#484B48",
      "800": "#303030",
      "900": "#1A1A1A",
      "1000": "#060606"
    },
    "white": {
      "100": "#FFFFFF0D",
      "200": "#FFFFFF1A",
      "300": "#FFFFFF33",
      "400": "#FFFFFF66",
      "500": "#FFFFFFB3",
      "600": "#FFFFFFCC",
      "700": "#FFFFFFD9",
      "800": "#FFFFFFE6",
      "900": "#FFFFFFF2",
      "1000": "#FFFFFF"
    },
    "black": {
      "100": "#0C0C0D0D",
      "160": "#0C0C0D14",
      "200": "#0C0C0D1A",
      "220": "#0C0C0D1F",
      "240": "#0C0C0D24",
      "260": "#0C0C0D29",
      "300": "#0C0C0D33",
      "400": "#0C0C0D66",
      "500": "#0C0C0DB3",
      "600": "#0C0C0DCC",
      "700": "#0C0C0DD9",
      "800": "#0C0C0DE6",
      "900": "#0C0C0DF2",
      "1000": "#0C0C0DFF"
    },
    "background": {
      "base": {
        "primary": "#FFFFFF",
        "primary-hover": "#F5F5F5",
        "secondary": "#F5F5F5",
        "secondary-hover": "#D7D7D7",
        "tertiary": "#D7D7D7",
        "tertiary-hover": "#B9B9B9",
        "inverse": "#1A1A1A",
        "inverse-hover": "#303030"
      },
      "neutral": {
        "primary": "#484B48",
        "primary-hover": "#303030",
        "secondary": "#D7D7D7",
        "secondary-hover": "#B9B9B9",
        "tertiary": "#F5F5F5",
        "tertiary-hover": "#D7D7D7"
      },
      "brand-magenta": {
        "primary": "#C76EF2",
        "primary-hover": "#D78FFB",
        "secondary": "#EED4FD",
        "secondary-hover": "#DFABF7",
        "tertiary": "#F9F1FE",
        "tertiary-hover": "#EED4FD",
        "strong": "#7C309D",
        "strong-hover": "#581074"
      },
      "brand-coral": {
        "primary": "#FF5A56",
        "primary-hover": "#FC8C84",
        "secondary": "#FED4CF",
        "secondary-hover": "#FDB2AA",
        "tertiary": "#FFF3F3",
        "tertiary-hover": "#FED4CF",
        "strong": "#A5161F",
        "strong-hover": "#730710"
      },
      "brand-green": {
        "primary": "#79FD7F",
        "primary-hover": "#9AFD9E",
        "secondary": "#D1FCD6",
        "secondary-hover": "#B7FDBB",
        "tertiary": "#E9FBF0",
        "tertiary-hover": "#D1FCD6",
        "strong": "#1C952C",
        "strong-hover": "#0B6318"
      },
      "brand-orange": {
        "primary": "#FFA000",
        "primary-hover": "#FCB86B",
        "secondary": "#FEE7CE",
        "secondary-hover": "#FDCD9B",
        "tertiary": "#FFF3E7",
        "tertiary-hover": "#FEE7CE",
        "strong": "#925C0E",
        "strong-hover": "#623C05"
      },
      "brand-blue": {
        "primary": "#0A58EA",
        "primary-hover": "#0645BD",
        "secondary": "#BAD2FD",
        "secondary-hover": "#82ADFB",
        "tertiary": "#F3F7FF",
        "tertiary-hover": "#BAD2FD",
        "strong": "#023392",
        "strong-hover": "#00216A"
      },
      "success": {
        "bold": "#79FD7F",
        "light": "#E9FBF0",
        "bold-hover": "#9AFD9E",
        "light-hover": "#D1FCD6"
      },
      "warning": {
        "bold": "#FFA000",
        "light": "#FFF3E7",
        "bold-hover": "#FCB86B",
        "light-hover": "#FEE7CE"
      },
      "danger": {
        "bold": "#FF5A56",
        "light": "#FFF3F3",
        "bold-hover": "#FC8C84",
        "light-hover": "#FED4CF"
      },
      "disabled": {
        "primary": "#D7D7D7"
      },
      "info": {
        "bold": "#0A58EA",
        "light": "#F3F7FF",
        "bold-hover": "#0645BD",
        "light-hover": "#BAD2FD"
      },
      "overlay": {
        "default": "#0C0C0D33",
        "inverse": "#FFFFFF33"
      },
      "scrim": {
        "default": "#0C0C0DB3"
      },
      "frosted": {
        "default": "#FFFFFFD9",
        "inverse": "#0C0C0D66"
      },
      "selected": {
        "default": "#F7F5FF"
      },
      "brand-yellow": {
        "primary": "#FFE60A",
        "primary-hover": "#FFEB60",
        "secondary": "#FFF5AD",
        "secondary-hover": "#FFF08A",
        "tertiary": "#FFF9CC",
        "tertiary-hover": "#FFF5AD",
        "strong": "#908215",
        "strong-hover": "#5E5509"
      },
      "brand-violet": {
        "primary": "#6D46FC",
        "primary-hover": "#572BD7",
        "secondary": "#CFCFFD",
        "secondary-hover": "#AAA8FB",
        "tertiary": "#F7F5FF",
        "tertiary-hover": "#CFCFFD",
        "strong": "#420EAE",
        "strong-hover": "#2E1781"
      }
    },
    "text": {
      "default": {
        "primary": "#1A1A1A",
        "secondary": "#636363",
        "tertiary": "#9B9B9B",
        "primary-inverse": "#FFFFFF"
      },
      "brand-magenta": {
        "primary": "#7C309D",
        "secondary": "#A14EC7",
        "primary-inverse": "#C76EF2",
        "on-primary": "#330146",
        "on-secondary": "#330146",
        "on-tertiary": "#330146",
        "on-strong": "#FFFFFF"
      },
      "brand-coral": {
        "primary": "#A5161F",
        "secondary": "#D23A3A",
        "primary-inverse": "#FF5A56",
        "on-primary": "#430105",
        "on-secondary": "#430105",
        "on-tertiary": "#430105",
        "on-strong": "#FFFFFF"
      },
      "brand-green": {
        "primary": "#1C952C",
        "secondary": "#4CC855",
        "primary-inverse": "#79FD7F",
        "on-primary": "#023407",
        "on-secondary": "#023407",
        "on-tertiary": "#023407",
        "on-strong": "#FFFFFF"
      },
      "brand-orange": {
        "primary": "#925C0E",
        "secondary": "#C67E18",
        "primary-inverse": "#FFA000",
        "on-primary": "#361E00",
        "on-secondary": "#361E00",
        "on-tertiary": "#361E00",
        "on-strong": "#FFFFFF"
      },
      "brand-blue": {
        "primary": "#023392",
        "secondary": "#0645BD",
        "primary-inverse": "#0A58EA",
        "on-primary": "#FFFFFF",
        "on-secondary": "#001046",
        "on-tertiary": "#001046",
        "on-strong": "#FFFFFF"
      },
      "success": {
        "on-bold": "#023407",
        "on-light": "#0B6318"
      },
      "warning": {
        "on-bold": "#361E00",
        "on-light": "#925C0E"
      },
      "danger": {
        "on-bold": "#430105",
        "on-light": "#A5161F"
      },
      "disabled": {
        "primary": "#9B9B9B"
      },
      "info": {
        "on-bold": "#FFFFFF",
        "on-light": "#023392"
      },
      "brand-yellow": {
        "primary": "#908215",
        "secondary": "#C6B321",
        "primary-inverse": "#FFE60A",
        "on-primary": "#312B01",
        "on-secondary": "#312B01",
        "on-tertiary": "#312B01",
        "on-strong": "#FFFFFF"
      },
      "utilities": {
        "on-overlay": "#FFFFFF"
      },
      "brand-violet": {
        "primary": "#420EAE",
        "secondary": "#572BD7",
        "primary-inverse": "#6D46FC",
        "on-primary": "#FFFFFF",
        "on-secondary": "#170751",
        "on-tertiary": "#170751",
        "on-strong": "#FFFFFF"
      },
      "link": {
        "default": "#420EAE",
        "visited": "#7C309D"
      }
    },
    "icon": {
      "default": {
        "primary": "#1A1A1A",
        "secondary": "#636363",
        "tertiary": "#9B9B9B",
        "primary-inverse": "#FFFFFF"
      },
      "brand-magenta": {
        "primary": "#7C309D",
        "on-primary": "#330146",
        "on-secondary": "#330146",
        "on-tertiary": "#330146",
        "on-strong": "#FFFFFF"
      },
      "brand-coral": {
        "primary": "#A5161F",
        "on-primary": "#430105",
        "on-secondary": "#430105",
        "on-tertiary": "#430105",
        "on-strong": "#FFFFFF"
      },
      "brand-green": {
        "primary": "#1C952C",
        "on-primary": "#023407",
        "on-secondary": "#023407",
        "on-tertiary": "#023407",
        "on-strong": "#FFFFFF"
      },
      "brand-orange": {
        "primary": "#925C0E",
        "on-primary": "#361E00",
        "on-secondary": "#361E00",
        "on-tertiary": "#361E00",
        "on-strong": "#FFFFFF"
      },
      "brand-blue": {
        "primary": "#023392",
        "on-primary": "#FFFFFF",
        "on-secondary": "#001046",
        "on-tertiary": "#001046",
        "on-strong": "#FFFFFF"
      },
      "success": {
        "on-bold": "#023407",
        "on-light": "#0B6318"
      },
      "warning": {
        "on-bold": "#361E00",
        "on-light": "#925C0E"
      },
      "danger": {
        "on-bold": "#430105",
        "on-light": "#A5161F"
      },
      "disabled": {
        "primary": "#9B9B9B"
      },
      "info": {
        "on-bold": "#FFFFFF",
        "on-light": "#023392"
      },
      "brand-yellow": {
        "primary": "#908215",
        "on-primary": "#312B01",
        "on-secondary": "#312B01",
        "on-tertiary": "#312B01",
        "on-strong": "#FFFFFF"
      },
      "brand-violet": {
        "primary": "#420EAE",
        "on-primary": "#FFFFFF",
        "on-secondary": "#170751",
        "on-tertiary": "#170751",
        "on-strong": "#FFFFFF"
      }
    },
    "border": {
      "default": {
        "primary": "#D7D7D7",
        "secondary": "#7F7F7F",
        "tertiary": "#484B48"
      },
      "focus": {
        "default": "#572BD7",
        "on-fill": "#1A1A1A"
      },
      "brand-magenta": {
        "primary": "#7C309D",
        "secondary": "#C76EF2",
        "tertiary": "#DFABF7"
      },
      "brand-coral": {
        "primary": "#A5161F",
        "secondary": "#FF5A56",
        "tertiary": "#FDB2AA"
      },
      "brand-green": {
        "primary": "#1C952C",
        "secondary": "#79FD7F",
        "tertiary": "#B7FDBB"
      },
      "brand-orange": {
        "primary": "#925C0E",
        "secondary": "#FFA000",
        "tertiary": "#FDCD9B"
      },
      "brand-blue": {
        "primary": "#023392",
        "secondary": "#0A58EA",
        "tertiary": "#82ADFB"
      },
      "success": {
        "primary": "#1C952C",
        "secondary": "#79FD7F",
        "tertiary": "#B7FDBB"
      },
      "warning": {
        "primary": "#C67E18",
        "secondary": "#FFA000",
        "tertiary": "#FDCD9B"
      },
      "danger": {
        "primary": "#D23A3A",
        "secondary": "#FF5A56",
        "tertiary": "#FDB2AA"
      },
      "disabled": {
        "default": "#D7D7D7"
      },
      "info": {
        "primary": "#0645BD",
        "secondary": "#0A58EA",
        "tertiary": "#82ADFB"
      },
      "selected": {
        "default": "#572BD7"
      },
      "brand-yellow": {
        "primary": "#908215",
        "secondary": "#FFE60A",
        "tertiary": "#FFF08A"
      },
      "utilities": {
        "swatch": "#0C0C0D33"
      },
      "brand-violet": {
        "primary": "#420EAE",
        "secondary": "#6D46FC",
        "tertiary": "#AAA8FB"
      }
    },
    "data-viz": {
      "1": "#6D46FC",
      "2": "#79FD7F",
      "3": "#FF5A56",
      "4": "#FFA000",
      "5": "#0A58EA",
      "6": "#C76EF2",
      "7": "#FFE60A",
      "8": "#7F7F7F"
    },
    "social": {
      "whatsapp": "#25D366",
      "telegram": "#229ED9",
      "facebook": "#1877F2",
      "vk": "#0077FF",
      "messenger": "#0084FF",
      "x": "#000000",
      "viber": "#7360F2",
      "line": "#06C755",
      "kakaotalk": "#FEE500"
    },
    "alpha": {
      "white": {
        "100": "#FFFFFF0D",
        "200": "#FFFFFF1A",
        "300": "#FFFFFF33",
        "400": "#FFFFFF66",
        "500": "#FFFFFFB3",
        "600": "#FFFFFFCC",
        "700": "#FFFFFFD9",
        "800": "#FFFFFFE6",
        "900": "#FFFFFFF2",
        "1000": "#FFFFFF"
      },
      "black": {
        "100": "#0C0C0D0D",
        "160": "#0C0C0D14",
        "200": "#0C0C0D1A",
        "220": "#0C0C0D1F",
        "240": "#0C0C0D24",
        "260": "#0C0C0D29",
        "300": "#0C0C0D33",
        "400": "#0C0C0D66",
        "500": "#0C0C0DB3",
        "600": "#0C0C0DCC",
        "700": "#0C0C0DD9",
        "800": "#0C0C0DE6",
        "900": "#0C0C0DF2",
        "1000": "#0C0C0DFF"
      }
    },
    "gradient": {
      "brand-spark": "linear-gradient(135deg, #6D46FC 0%, #C76EF2 100%)",
      "deep-space": "linear-gradient(160deg, #2E1781 0%, #0645BD 100%)",
      "sunrise": "linear-gradient(120deg, #FC8C84 0%, #FFEB60 100%)",
      "mango": "linear-gradient(135deg, #FFA000 0%, #FFEB60 100%)",
      "lagoon": "linear-gradient(135deg, #0A58EA 0%, #9AFD9E 100%)",
      "berry": "linear-gradient(135deg, #A14EC7 0%, #FF5A56 100%)",
      "aurora": "linear-gradient(150deg, #6D46FC 0%, #D78FFB 55%, #FDB2AA 100%)",
      "mint-air": "linear-gradient(135deg, #D1FCD6 0%, #BAD2FD 100%)",
      "canvas-wash": "linear-gradient(180deg, #F7F5FF 0%, #F3F7FF 100%)",
      "night-glow": "linear-gradient(145deg, #170751 0%, #7C309D 100%)"
    }
  },
  "size": {
    "space": {
      "0": "0px",
      "100": "4px",
      "150": "6px",
      "200": "8px",
      "300": "12px",
      "400": "16px",
      "500": "20px",
      "600": "24px",
      "800": "32px",
      "1000": "40px",
      "1200": "48px",
      "1600": "64px",
      "1800": "72px",
      "2000": "80px",
      "2200": "88px",
      "2400": "96px",
      "3200": "128px",
      "4000": "160px",
      "050": "2px",
      "negative": {
        "100": "-4px",
        "150": "-6px",
        "200": "-8px",
        "300": "-12px",
        "400": "-16px",
        "500": "-20px",
        "600": "-24px",
        "800": "-32px",
        "1000": "-40px",
        "1200": "-48px",
        "1600": "-64px",
        "1800": "-72px",
        "2000": "-80px",
        "2200": "-88px",
        "2400": "-96px",
        "3200": "-128px",
        "4000": "-160px",
        "050": "-2px"
      }
    },
    "radius": {
      "0": "0px",
      "100": "4px",
      "150": "6px",
      "200": "8px",
      "300": "12px",
      "400": "16px",
      "500": "20px",
      "600": "24px",
      "800": "32px",
      "900": "40px",
      "050": "2px",
      "full": "9999px"
    },
    "stroke": {
      "border": "1px"
    },
    "icon": {
      "small": "24px",
      "medium": "32px",
      "large": "40px"
    },
    "blur": {
      "100": "4px",
      "200": "8px",
      "300": "12px",
      "400": "16px",
      "500": "24px",
      "600": "32px",
      "700": "36px"
    },
    "depth": {
      "0": "0px",
      "100": "4px",
      "200": "8px",
      "300": "12px",
      "400": "16px",
      "025": "1px"
    },
    "focus": {
      "ring": "2px",
      "offset": "2px"
    }
  },
  "typography": {
    "family": {
      "sans": "Mikado"
    },
    "weight": {
      "regular": 400,
      "bold": 700
    },
    "size": {
      "10": "10px",
      "12": "12px",
      "14": "14px",
      "16": "16px",
      "18": "18px",
      "20": "20px",
      "24": "24px",
      "28": "28px",
      "32": "32px",
      "36": "36px",
      "40": "40px",
      "48": "48px",
      "60": "60px",
      "72": "72px"
    },
    "line-height": {
      "100": 1,
      "110": 1.1,
      "120": 1.2,
      "130": 1.3,
      "140": 1.4,
      "150": 1.5
    },
    "letter-spacing": {
      "none": "0px",
      "wide": "0.5px",
      "wider": "1px"
    },
    "display": {
      "lg": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "60px",
        "line-height": "100%",
        "letter-spacing": "0px"
      },
      "md": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "48px",
        "line-height": "100%",
        "letter-spacing": "0px"
      },
      "sm": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "40px",
        "line-height": "100%",
        "letter-spacing": "0px"
      },
      "xs": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "36px",
        "line-height": "100%",
        "letter-spacing": "0px"
      }
    },
    "heading": {
      "lg": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "32px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "md": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "24px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "sm": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "20px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "xs": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "16px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "lg-regular": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "32px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "md-regular": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "24px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "sm-regular": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "20px",
        "line-height": "130%",
        "letter-spacing": "0px"
      },
      "xs-regular": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "16px",
        "line-height": "130%",
        "letter-spacing": "0px"
      }
    },
    "body": {
      "lg": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "18px",
        "line-height": "140%",
        "letter-spacing": "0px"
      },
      "md": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "16px",
        "line-height": "140%",
        "letter-spacing": "0px"
      },
      "sm": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "14px",
        "line-height": "140%",
        "letter-spacing": "0px"
      },
      "lg-strong": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "18px",
        "line-height": "140%",
        "letter-spacing": "0px"
      },
      "md-strong": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "16px",
        "line-height": "140%",
        "letter-spacing": "0px"
      },
      "sm-strong": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "14px",
        "line-height": "140%",
        "letter-spacing": "0px"
      }
    },
    "label": {
      "lg": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "16px",
        "line-height": "100%",
        "letter-spacing": "0.5px"
      },
      "sm": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "14px",
        "line-height": "100%",
        "letter-spacing": "0.5px"
      }
    },
    "caption": {
      "default": {
        "font-family": "Mikado",
        "font-weight": 400,
        "font-size": "12px",
        "line-height": "140%",
        "letter-spacing": "0px"
      },
      "strong": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "12px",
        "line-height": "140%",
        "letter-spacing": "0px"
      }
    },
    "overline": {
      "default": {
        "font-family": "Mikado",
        "font-weight": 700,
        "font-size": "10px",
        "line-height": "150%",
        "letter-spacing": "1px"
      }
    }
  },
  "effect": {
    "drop-shadow": {
      "100": "0px 1px 4px 0px #0C0C0D14",
      "200": "0px 1px 4px 0px #0C0C0D0D, 0px 4px 8px 0px #0C0C0D1F",
      "300": "0px 1px 4px 0px #0C0C0D0D, 0px 4px 16px 0px #0C0C0D24",
      "400": "0px 1px 4px 0px #0C0C0D0D, 0px 8px 24px 0px #0C0C0D29",
      "500": "0px 1px 4px 0px #0C0C0D0D, 0px 12px 32px 0px #0C0C0D29",
      "600": "0px 16px 36px 0px #0C0C0D33"
    },
    "inner-shadow": {
      "100": "inset 0px 1px 4px 0px #0C0C0D14",
      "200": "inset 0px 4px 8px 0px #0C0C0D29"
    },
    "backdrop": {
      "overlay": "8px",
      "scrim": "16px",
      "glass": "24px",
      "heavy": "40px"
    },
    "opacity": {
      "0": 0,
      "10": 0.1,
      "20": 0.2,
      "30": 0.3,
      "40": 0.4,
      "50": 0.5,
      "60": 0.6,
      "70": 0.7,
      "80": 0.8,
      "90": 0.9,
      "100": 1,
      "disabled": 0.4,
      "muted": 0.6
    }
  },
  "motion": {
    "duration": {
      "fast": "100ms",
      "base": "200ms",
      "slow": "300ms",
      "slower": "500ms"
    },
    "easing": {
      "standard": "cubic-bezier(0.2, 0, 0, 1)",
      "decelerate": "cubic-bezier(0, 0, 0, 1)",
      "accelerate": "cubic-bezier(0.3, 0, 1, 1)"
    }
  },
  "z-index": {
    "base": 0,
    "dropdown": 1000,
    "sticky": 1100,
    "overlay": 1200,
    "modal": 1300,
    "toast": 1400
  },
  "responsive": {
    "mobile": {
      "device": "mobile",
      "breakpoint-min": "0px",
      "device-width": "375px",
      "columns": 2,
      "gutter": "16px",
      "margin": "16px",
      "root-font-size": "16px"
    },
    "tablet": {
      "device": "tablet",
      "breakpoint-min": "768px",
      "device-width": "768px",
      "columns": 8,
      "gutter": "16px",
      "margin": "24px",
      "root-font-size": "16px"
    },
    "desktop": {
      "device": "desktop",
      "breakpoint-min": "1280px",
      "device-width": "1440px",
      "columns": 12,
      "gutter": "16px",
      "margin": "152px",
      "root-font-size": "16px"
    },
    "wide": {
      "device": "wide",
      "breakpoint-min": "1920px",
      "device-width": "1920px",
      "columns": 12,
      "gutter": "32px",
      "margin": "160px",
      "root-font-size": "16px"
    }
  }
} as const;

export type NkTokens = typeof tokens;
export default tokens;
